export enum FlowersEnum {
    TRANDAFIR = "Trandafir",
    LILIAC = "Liliac",
    MARGARETA = "Margaretă",
    GIRASOL = "Girasol",
    GAROAFA = "Garoafa",
    CRIN = "Crin",
    ORHIDEE = "Orhidee",
    CRIN_DE_PADURE = "Crin de Pădure",
    MAC = "Mac",
    ZAMBILA = "Zambila",
    BUCIUM_DE_MAI = "Bucium de Mai",
    GIGEL = "Gigel",
    GERBERA = "Gerbera",
    CRIN_IRIS = "Crin Iris",
    ASTER = "Aster",
    CRIZANTEMA = "Crizantemă",
    LAVANDĂ = "Levănțică",
    IASOMIE = "Iasomie",
    NARCISA = "Narcisă",
    AZALEE = "Azalee",
    HIBISCUS = "Hibiscus",
    CRINUL_PACII = "Crinul Păcii",
    GÂZANIE = "Gâzanie",
    VIOLETA = "Viola",
    ZINNIA = "Zinnia",
    CAMELIA = "Camelia",
    LALEA = "Lalea"
}

